In [2]:
import pandas as pd
import numpy as np
import torch

In [3]:
print(torch.__version__)

1.7.1


In [11]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [12]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, requires_grad=True, device=device)

In [13]:
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [23]:
x = torch.zeros(3, 2)

In [25]:
torch.ones(1, 2, 3)

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [27]:
torch.eye(5, 5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [29]:
torch.linspace(0, 1, 5)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [30]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [34]:
torch.empty(3, 3).normal_(0, 1)

tensor([[-0.3043,  0.4596, -1.3746],
        [-1.0959, -0.5235, -0.2800],
        [-1.7771, -0.5355, -1.5811]])

In [37]:
torch.diag(torch.ones(5, 4))

tensor([1., 1., 1., 1.])

In [49]:
torch.arange(4).half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [50]:
torch.arange(5).double()

tensor([0., 1., 2., 3., 4.], dtype=torch.float64)

In [51]:
tensor = torch.arange(10)

In [55]:
tensor.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
torch.from_numpy(np.array([1, 2, 3, 4, 5]))

tensor([1, 2, 3, 4, 5])

In [58]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([5, 6, 7])

In [65]:
torch.add(x, y), x + y

(tensor([ 6,  8, 10]), tensor([ 6,  8, 10]))

In [64]:
torch.true_divide(x, y), x / y

(tensor([0.2000, 0.3333, 0.4286]), tensor([0.2000, 0.3333, 0.4286]))

In [66]:
x.add_(y)

tensor([ 6,  8, 10])

In [72]:
x.pow(2), x ** 2

(tensor([ 36,  64, 100]), tensor([ 36,  64, 100]))

In [90]:
x = torch.rand(size=(2, 3))
y = torch.rand(size=(2, 3))

In [91]:
x.mm(y.T)

tensor([[0.5482, 0.8885],
        [0.7538, 0.2255]])

In [94]:
x, y

(tensor([[0.4492, 0.7136, 0.0761],
         [0.0767, 0.2120, 0.8007]]),
 tensor([[0.6759, 0.2564, 0.8088],
         [0.8729, 0.6940, 0.0142]]))

In [95]:
x*y

tensor([[0.3036, 0.1830, 0.0616],
        [0.0669, 0.1472, 0.0114]])

In [102]:
values, indices = x.max(dim=0)

In [103]:
values, indices

(tensor([0.4492, 0.7136, 0.8007]), tensor([0, 0, 1]))

In [104]:
torch.eq(x, y)

tensor([[False, False, False],
        [False, False, False]])

In [112]:
values, indices = torch.sort(x, dim=0)

In [113]:
values, indices

(tensor([[0.0767, 0.2120, 0.0761],
         [0.4492, 0.7136, 0.8007]]),
 tensor([[1, 1, 0],
         [0, 0, 1]]))

In [114]:
batch_size = 10
features = 25

x = torch.rand((batch_size, features))

x.shape

torch.Size([10, 25])